# Generated by Django 6.0.8 on 2026-09-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.PositiveIntegerField(default=0)),
                ('recompenses', models.PositiveIntegerField(default=0)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fidelite', to='loyalty.client')),
            ],
        ),
    ]
