# Generated by Django 6.0.8 on 2026-09-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_fidelite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartePrepayee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafes_restants', models.PositiveIntegerField(default=11)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_prepayees', to='loyalty.client')),
            ],
        ),
    ]
