# Generated by Django 6.0.8 on 2026-09-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_carteprepayee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_achat', models.CharField(choices=[('PAYANT', 'Payant'), ('GRATUIT_FIDELITE', 'Gratuit - fidelite'), ('PREPAYE', 'Prepayé')], default='PAYANT', max_length=20)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('carte_prepayee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='loyalty.carteprepayee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='loyalty.client')),
            ],
        ),
    ]
